/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppModal {
    }
    interface AppRoot {
    }
    interface PagesTour {
    }
}
declare global {
    interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {
    }
    var HTMLAppModalElement: {
        prototype: HTMLAppModalElement;
        new (): HTMLAppModalElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPagesTourElement extends Components.PagesTour, HTMLStencilElement {
    }
    var HTMLPagesTourElement: {
        prototype: HTMLPagesTourElement;
        new (): HTMLPagesTourElement;
    };
    interface HTMLElementTagNameMap {
        "app-modal": HTMLAppModalElement;
        "app-root": HTMLAppRootElement;
        "pages-tour": HTMLPagesTourElement;
    }
}
declare namespace LocalJSX {
    interface AppModal {
    }
    interface AppRoot {
    }
    interface PagesTour {
    }
    interface IntrinsicElements {
        "app-modal": AppModal;
        "app-root": AppRoot;
        "pages-tour": PagesTour;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-modal": LocalJSX.AppModal & JSXBase.HTMLAttributes<HTMLAppModalElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pages-tour": LocalJSX.PagesTour & JSXBase.HTMLAttributes<HTMLPagesTourElement>;
        }
    }
}
